//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeLi.MengSang.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeLi.MengSang.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arm {
            get {
                object obj = ResourceManager.GetObject("Arm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        internal static string BangZhu {
            get {
                return ResourceManager.GetString("BangZhu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可丢弃.
        /// </summary>
        internal static string BuKe_DiuQi {
            get {
                return ResourceManager.GetString("BuKe_DiuQi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可分解.
        /// </summary>
        internal static string BuKe_FenJie {
            get {
                return ResourceManager.GetString("BuKe_FenJie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成就.
        /// </summary>
        internal static string ChengJiu {
            get {
                return ResourceManager.GetString("ChengJiu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 城镇.
        /// </summary>
        internal static string ChengZhen {
            get {
                return ResourceManager.GetString("ChengZhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 充值.
        /// </summary>
        internal static string ChongZhi {
            get {
                return ResourceManager.GetString("ChongZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建房间.
        /// </summary>
        internal static string ChuangJian_FangJian {
            get {
                return ResourceManager.GetString("ChuangJian_FangJian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 苍雷*帝恨护手.
        /// </summary>
        internal static string CL_DL_HuShou {
            get {
                return ResourceManager.GetString("CL_DL_HuShou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 苍雷*帝恨护手[10阶]+15.
        /// </summary>
        internal static string CL_DL_HuShou_15 {
            get {
                return ResourceManager.GetString("CL_DL_HuShou_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 苍雷*帝恨戒指.
        /// </summary>
        internal static string CL_DL_JieZhi {
            get {
                return ResourceManager.GetString("CL_DL_JieZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 苍雷*帝恨套装[7/7][第七章装备].
        /// </summary>
        internal static string CL_DL_TaoZhuang {
            get {
                return ResourceManager.GetString("CL_DL_TaoZhuang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 苍雷*帝恨项链.
        /// </summary>
        internal static string CL_DL_XiangLian {
            get {
                return ResourceManager.GetString("CL_DL_XiangLian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 苍雷*帝恨腰带.
        /// </summary>
        internal static string CL_DL_YaoDai {
            get {
                return ResourceManager.GetString("CL_DL_YaoDai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 苍雷*天征印.
        /// </summary>
        internal static string CL_DL_Yin {
            get {
                return ResourceManager.GetString("CL_DL_Yin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 苍雷*帝恨战铠.
        /// </summary>
        internal static string CL_DL_ZhanKai {
            get {
                return ResourceManager.GetString("CL_DL_ZhanKai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 苍雷*帝恨战靴.
        /// </summary>
        internal static string CL_DL_ZhanXue {
            get {
                return ResourceManager.GetString("CL_DL_ZhanXue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存档.
        /// </summary>
        internal static string CunDang {
            get {
                return ResourceManager.GetString("CunDang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间列表.
        /// </summary>
        internal static string FangJian_LieBiao {
            get {
                return ResourceManager.GetString("FangJian_LieBiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非玩家列表.
        /// </summary>
        internal static string FeiWanJia_LieBiao {
            get {
                return ResourceManager.GetString("FeiWanJia_LieBiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 副本任务.
        /// </summary>
        internal static string FuBen_RenWu {
            get {
                return ResourceManager.GetString("FuBen_RenWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Furnish {
            get {
                object obj = ResourceManager.GetObject("Furnish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人.
        /// </summary>
        internal static string GeRen {
            get {
                return ResourceManager.GetString("GeRen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 功勋.
        /// </summary>
        internal static string GongXun {
            get {
                return ResourceManager.GetString("GongXun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好友.
        /// </summary>
        internal static string HaoYou {
            get {
                return ResourceManager.GetString("HaoYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hero {
            get {
                object obj = ResourceManager.GetObject("Hero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回归奖励.
        /// </summary>
        internal static string HuiGui_JiangLi {
            get {
                return ResourceManager.GetString("HuiGui_JiangLi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 攻击时有20.0%几率触发，对周围550码内的敌军造成[5550.0+主属性*0.15]点伤害.
        /// </summary>
        internal static string JiNeng_MiaoShu1 {
            get {
                return ResourceManager.GetString("JiNeng_MiaoShu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 攻击时有20.0%几率触发，召唤[8]颗陨石对周围900码内的敌军单位打击，造成[主属性*1.1]点额外伤害.
        /// </summary>
        internal static string JiNeng_MiaoShu2 {
            get {
                return ResourceManager.GetString("JiNeng_MiaoShu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏初始金钱提高25.0%.
        /// </summary>
        internal static string JiNeng_MiaoShu3 {
            get {
                return ResourceManager.GetString("JiNeng_MiaoShu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提升自身520.0点全属性，提高13.5%倍击几率.
        /// </summary>
        internal static string JiNeng_MiaoShu4 {
            get {
                return ResourceManager.GetString("JiNeng_MiaoShu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冰封万里 Lv.7.
        /// </summary>
        internal static string JiNeng_MingCheng1 {
            get {
                return ResourceManager.GetString("JiNeng_MingCheng1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 归于混沌 Lv.3.
        /// </summary>
        internal static string JiNeng_MingCheng2 {
            get {
                return ResourceManager.GetString("JiNeng_MingCheng2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 富极之尊 Lv.8.
        /// </summary>
        internal static string JiNeng_MingCheng3 {
            get {
                return ResourceManager.GetString("JiNeng_MingCheng3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无情之心 Lv.9.
        /// </summary>
        internal static string JiNeng_MingCheng4 {
            get {
                return ResourceManager.GetString("JiNeng_MingCheng4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始匹配.
        /// </summary>
        internal static string KaiShi_PiPei {
            get {
                return ResourceManager.GetString("KaiShi_PiPei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 炼化加成.
        /// </summary>
        internal static string LianHua_JiaCheng {
            get {
                return ResourceManager.GetString("LianHua_JiaCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1000.0点力量.
        /// </summary>
        internal static string LiLiang_1000 {
            get {
                return ResourceManager.GetString("LiLiang_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2550.0点力量.
        /// </summary>
        internal static string LiLiang_2550 {
            get {
                return ResourceManager.GetString("LiLiang_2550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +3950.0点魂力.
        /// </summary>
        internal static string LingLi_3950 {
            get {
                return ResourceManager.GetString("LingLi_3950", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft YaHei.
        /// </summary>
        internal static string Microsoft_YaHei {
            get {
                return ResourceManager.GetString("Microsoft_YaHei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1550.0点敏捷.
        /// </summary>
        internal static string MinJie_1550 {
            get {
                return ResourceManager.GetString("MinJie_1550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排行榜.
        /// </summary>
        internal static string PaiHangBang {
            get {
                return ResourceManager.GetString("PaiHangBang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匹配.
        /// </summary>
        internal static string PiPei {
            get {
                return ResourceManager.GetString("PiPei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +86.0点破甲.
        /// </summary>
        internal static string PoJia_86 {
            get {
                return ResourceManager.GetString("PoJia_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务.
        /// </summary>
        internal static string RenWu {
            get {
                return ResourceManager.GetString("RenWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商城.
        /// </summary>
        internal static string ShangCheng {
            get {
                return ResourceManager.GetString("ShangCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社会.
        /// </summary>
        internal static string SheHui {
            get {
                return ResourceManager.GetString("SheHui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水岭注.
        /// </summary>
        internal static string ShuiLingZhu {
            get {
                return ResourceManager.GetString("ShuiLingZhu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索房间....
        /// </summary>
        internal static string SouSuo_FangJian {
            get {
                return ResourceManager.GetString("SouSuo_FangJian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;所有地图&gt;.
        /// </summary>
        internal static string SuoYou_DiTu {
            get {
                return ResourceManager.GetString("SuoYou_DiTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家列表.
        /// </summary>
        internal static string WanJia_LieBiao {
            get {
                return ResourceManager.GetString("WanJia_LieBiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 张翼德之力.
        /// </summary>
        internal static string WanJia_MingCheng {
            get {
                return ResourceManager.GetString("WanJia_MingCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你好，张翼德！.
        /// </summary>
        internal static string WanJia_XiaoXi {
            get {
                return ResourceManager.GetString("WanJia_XiaoXi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武器&gt;单手.
        /// </summary>
        internal static string WuQi_DanShou {
            get {
                return ResourceManager.GetString("WuQi_DanShou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ★★★★★★★★★★★★★★★.
        /// </summary>
        internal static string WuXing {
            get {
                return ResourceManager.GetString("WuXing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 镶嵌加成.
        /// </summary>
        internal static string XiangQian_JiaCheng {
            get {
                return ResourceManager.GetString("XiangQian_JiaCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 西凉战神元神卡 Lv.5.
        /// </summary>
        internal static string XiangQianKa_MingCheng {
            get {
                return ResourceManager.GetString("XiangQianKa_MingCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幸运.
        /// </summary>
        internal static string XingYun {
            get {
                return ResourceManager.GetString("XingYun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 湮灭*星陨刀.
        /// </summary>
        internal static string YanMie_XingYunDao {
            get {
                return ResourceManager.GetString("YanMie_XingYunDao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 湮灭*星陨刀[10阶]+15.
        /// </summary>
        internal static string YanMie_XingYunDao_15 {
            get {
                return ResourceManager.GetString("YanMie_XingYunDao_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 湮灭*星陨对戟.
        /// </summary>
        internal static string YanMie_XingYunDuiJi {
            get {
                return ResourceManager.GetString("YanMie_XingYunDuiJi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 湮灭*星陨弓.
        /// </summary>
        internal static string YanMie_XingYunGong {
            get {
                return ResourceManager.GetString("YanMie_XingYunGong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 湮灭*星陨枪.
        /// </summary>
        internal static string YanMie_XingYunQiang {
            get {
                return ResourceManager.GetString("YanMie_XingYunQiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 湮灭*星陨套装[5/5][第七章装备].
        /// </summary>
        internal static string YanMie_XingYunTaoZhuang {
            get {
                return ResourceManager.GetString("YanMie_XingYunTaoZhuang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 湮灭*星陨爪.
        /// </summary>
        internal static string YanMie_XingYunZhua {
            get {
                return ResourceManager.GetString("YanMie_XingYunZhua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已绑定.
        /// </summary>
        internal static string YiBangDing {
            get {
                return ResourceManager.GetString("YiBangDing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游乐园.
        /// </summary>
        internal static string YouLeYuan {
            get {
                return ResourceManager.GetString("YouLeYuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 增益效果.
        /// </summary>
        internal static string ZengYi_XiaoGuo {
            get {
                return ResourceManager.GetString("ZengYi_XiaoGuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 珍宝阁.
        /// </summary>
        internal static string ZhenBaoGe {
            get {
                return ResourceManager.GetString("ZhenBaoGe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直播.
        /// </summary>
        internal static string ZhiBo {
            get {
                return ResourceManager.GetString("ZhiBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1550.0点智力.
        /// </summary>
        internal static string ZhiLi_1550 {
            get {
                return ResourceManager.GetString("ZhiLi_1550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 周年庆.
        /// </summary>
        internal static string ZhouNianQing {
            get {
                return ResourceManager.GetString("ZhouNianQing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 神兵一出，冰封万里，百万神魔瞬间灰飞烟灭！.
        /// </summary>
        internal static string ZhuangBei_GuShi {
            get {
                return ResourceManager.GetString("ZhuangBei_GuShi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装备&gt;护手.
        /// </summary>
        internal static string ZhuangBei_HuShou {
            get {
                return ResourceManager.GetString("ZhuangBei_HuShou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装备附加的能力不带入竞技场.
        /// </summary>
        internal static string ZhuangBei_ShuoMing {
            get {
                return ResourceManager.GetString("ZhuangBei_ShuoMing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 综合.
        /// </summary>
        internal static string ZongHe {
            get {
                return ResourceManager.GetString("ZongHe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组队.
        /// </summary>
        internal static string ZuDui {
            get {
                return ResourceManager.GetString("ZuDui", resourceCulture);
            }
        }
    }
}
